In [3]:
import pandas as pd
import sqlite3

In [4]:
df = pd.read_csv("../data/processed/cleaned_supermarket_sales.csv")
df.head()

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,Alex,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,1:08:00 PM,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,Giza,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29:00 AM,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,Alex,Yangon,Normal,Female,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,1:23:00 PM,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,Alex,Yangon,Member,Female,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,8:33:00 PM,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,Alex,Yangon,Member,Female,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37:00 AM,Ewallet,604.17,4.761905,30.2085,5.3

In [5]:
conn = sqlite3.connect("../database/sales.db")

In [6]:
df.to_sql("sales", conn, if_exists="replace", index=False)

print("Database Created Successfully")

Database Created Successfully

In [7]:
pd.read_sql("SELECT * FROM sales LIMIT 5;", conn)

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,Alex,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,1:08:00 PM,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,Giza,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29:00 AM,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,Alex,Yangon,Normal,Female,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,1:23:00 PM,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,Alex,Yangon,Member,Female,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,8:33:00 PM,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,Alex,Yangon,Member,Female,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37:00 AM,Ewallet,604.17,4.761905,30.2085,5.3

In [8]:
query = "SELECT * FROM sales;"
result = pd.read_sql(query, conn)
result.head()

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,Alex,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,1:08:00 PM,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,Giza,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29:00 AM,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,Alex,Yangon,Normal,Female,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,1:23:00 PM,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,Alex,Yangon,Member,Female,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,8:33:00 PM,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,Alex,Yangon,Member,Female,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37:00 AM,Ewallet,604.17,4.761905,30.2085,5.3

In [9]:
query = """
SELECT *
FROM sales
WHERE Gender = 'Female';
"""

result = pd.read_sql(query, conn)
result.head()

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,Alex,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,1:08:00 PM,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,Giza,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29:00 AM,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,Alex,Yangon,Normal,Female,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,1:23:00 PM,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,Alex,Yangon,Member,Female,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,8:33:00 PM,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,Alex,Yangon,Member,Female,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37:00 AM,Ewallet,604.17,4.761905,30.2085,5.3

In [10]:
query = """
SELECT *
FROM sales
ORDER BY Total DESC;
"""

result = pd.read_sql(query, conn)
result.head()

DatabaseError: Execution failed on sql '
SELECT *
FROM sales
ORDER BY Total DESC;
': no such column: Total

In [11]:
print(df.columns)

Index(['Invoice ID', 'Branch', 'City', 'Customer type', 'Gender',
       'Product line', 'Unit price', 'Quantity', 'Tax 5%', 'Sales', 'Date',
       'Time', 'Payment', 'cogs', 'gross margin percentage', 'gross income',
       'Rating'],
      dtype='str')

In [12]:
query = """
SELECT *
FROM sales
ORDER BY Sales DESC;
"""

result = pd.read_sql(query, conn)
result.head()

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,860-79-0874,Giza,Naypyitaw,Member,Female,Fashion accessories,99.30,10,49.65,1042.65,2/15/2019,2:53:00 PM,Credit card,993.0,4.761905,49.65,6.6
1,687-47-8271,Alex,Yangon,Normal,Male,Fashion accessories,98.98,10,49.49,1039.29,2/8/2019,4:20:00 PM,Credit card,989.8,4.761905,49.49,8.7
2,283-26-5248,Giza,Naypyitaw,Member,Female,Food and beverages,98.52,10,49.26,1034.46,1/30/2019,8:23:00 PM,Ewallet,985.2,4.761905,49.26,4.5
3,751-41-9720,Giza,Naypyitaw,Normal,Male,Home and lifestyle,97.50,10,48.75,1023.75,1/12/2019,4:18:00 PM,Ewallet,975.0,4.761905,48.75,8.0
4,303-96-2227,Cairo,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.69,1022.49,3/2/2019,5:16:00 PM,Ewallet,973.8,4.761905,48.69,4.4

In [13]:
query = """
SELECT *
FROM sales
LIMIT 10;
"""

result = pd.read_sql(query, conn)
result

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,Alex,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,1:08:00 PM,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,Giza,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29:00 AM,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,Alex,Yangon,Normal,Female,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,1:23:00 PM,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,Alex,Yangon,Member,Female,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,8:33:00 PM,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,Alex,Yangon,Member,Female,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37:00 AM,Ewallet,604.17,4.761905,30.2085,5.3
5,699-14-3026,Giza,Naypyitaw,Member,Female,Electronic accessories,85.39,7,29.8865,627.6165,3/25/2019,6:30:00 PM,Ewallet,597.73,4.761905,29.8865,4.1
6,355-53-5943,Alex,Yangon,Member,Female,Electronic accessories,68.84,6,20.6520,433.6920,2/25/2019,2:36:00 PM,Ewallet,413.04,4.761905,20.6520,5.8
7,315-22-5665,Giza,Naypyitaw,Member,Female,Home and lifestyle,73.56,10,36.7800,772.3800,2/24/2019,11:38:00 AM,Ewallet,735.60,4.761905,36.7800,8.0
8,665-32-9167,Alex,Yangon,Member,Female,Health and beauty,36.26,2,3.6260,76.1460,1/10/2019,5:15:00 PM,Credit card,72.52,4.761905,3.6260,7.2
9,692-92-5582,Cairo,Mandalay,Member,Female,Food and beverages,54.84,3,8.2260,172.7460,2/20/2019,1:27:00 PM,Credit card,164.52,4.761905,8.2260,5.9

In [14]:
query = """
SELECT COUNT(*) AS Total_Records
FROM sales;
"""

pd.read_sql(query, conn)

   Total_Records
0           1000

In [15]:
query = """
SELECT SUM(Sales) AS Total_Sales
FROM sales;
"""

pd.read_sql(query, conn)

   Total_Sales
0   322966.749

In [16]:
query = """
SELECT AVG(Sales) AS Average_Sales
FROM sales;
"""

pd.read_sql(query, conn)

   Average_Sales
0     322.966749

In [17]:
query = """
SELECT MIN(Sales) AS Minimum_Sales
FROM sales;
"""

pd.read_sql(query, conn)

   Minimum_Sales
0        10.6785

In [18]:
query = """
SELECT MAX(Sales) AS Maximum_Sales
FROM sales;
"""

pd.read_sql(query, conn)

   Maximum_Sales
0        1042.65

In [19]:
query = """
SELECT "Product line",
SUM(Sales) AS Total_Sales
FROM sales
GROUP BY "Product line";
"""

result = pd.read_sql(query, conn)
result

             Product line  Total_Sales
0  Electronic accessories   54337.5315
1     Fashion accessories   54305.8950
2      Food and beverages   56144.8440
3       Health and beauty   49193.7390
4      Home and lifestyle   53861.9130
5       Sports and travel   55122.8265

In [20]:
query = """
SELECT "Product line",
SUM(Sales) AS Total_Sales
FROM sales
GROUP BY "Product line"
HAVING SUM(Sales) > 50000;
"""

result = pd.read_sql(query, conn)
result

             Product line  Total_Sales
0  Electronic accessories   54337.5315
1     Fashion accessories   54305.8950
2      Food and beverages   56144.8440
3      Home and lifestyle   53861.9130
4       Sports and travel   55122.8265

In [21]:
query = """
SELECT "Product line",
AVG(Sales) AS Average_Sales
FROM sales
GROUP BY "Product line";
"""

result = pd.read_sql(query, conn)
result

             Product line  Average_Sales
0  Electronic accessories     319.632538
1     Fashion accessories     305.089298
2      Food and beverages     322.671517
3       Health and beauty     323.643020
4      Home and lifestyle     336.636956
5       Sports and travel     332.065220

In [22]:
query = """
SELECT City,
SUM(Sales) AS Total_Sales
FROM sales
GROUP BY City
ORDER BY Total_Sales DESC;
"""

result = pd.read_sql(query, conn)
result

        City  Total_Sales
0  Naypyitaw  110568.7065
1     Yangon  106200.3705
2   Mandalay  106197.6720

In [23]:
query = """
SELECT Payment,
COUNT(*) AS Total_Customers
FROM sales
GROUP BY Payment;
"""

result = pd.read_sql(query, conn)
result

       Payment  Total_Customers
0         Cash              344
1  Credit card              311
2      Ewallet              345

In [24]:
query = """
WITH AvgSales AS (
    SELECT AVG(Sales) AS avg_sales
    FROM sales
)

SELECT *
FROM sales, AvgSales
WHERE Sales > avg_sales;
"""

result = pd.read_sql(query, conn)
result.head()

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating,avg_sales
0,750-67-8428,Alex,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,1:08:00 PM,Ewallet,522.83,4.761905,26.1415,9.1,322.966749
1,631-41-3108,Alex,Yangon,Normal,Female,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,1:23:00 PM,Credit card,324.31,4.761905,16.2155,7.4,322.966749
2,123-19-1176,Alex,Yangon,Member,Female,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,8:33:00 PM,Ewallet,465.76,4.761905,23.2880,8.4,322.966749
3,373-73-7910,Alex,Yangon,Member,Female,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37:00 AM,Ewallet,604.17,4.761905,30.2085,5.3,322.966749
4,699-14-3026,Giza,Naypyitaw,Member,Female,Electronic accessories,85.39,7,29.8865,627.6165,3/25/2019,6:30:00 PM,Ewallet,597.73,4.761905,29.8865,4.1,322.966749

In [25]:
query = """
SELECT
    "Invoice ID",
    Sales,
    RANK() OVER (ORDER BY Sales DESC) AS Sales_Rank
FROM sales;
"""

result = pd.read_sql(query, conn)
result.head(10)

    Invoice ID     Sales  Sales_Rank
0  860-79-0874  1042.650           1
1  687-47-8271  1039.290           2
2  283-26-5248  1034.460           3
3  751-41-9720  1023.750           4
4  303-96-2227  1022.490           5
5  744-16-7898  1022.385           6
6  271-88-8734  1020.705           7
7  234-65-2137  1003.590           8
8  554-42-2417  1002.120           9
9  325-77-6186   951.825          10

In [26]:
query = """
CREATE VIEW HighSales AS
SELECT *
FROM sales
WHERE Sales > 500;
"""

conn.execute(query)
print("View Created Successfully!")

View Created Successfully!

In [27]:
query = "SELECT * FROM HighSales;"

result = pd.read_sql(query, conn)
result.head()

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,Alex,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,1:08:00 PM,Ewallet,522.83,4.761905,26.1415,9.1
1,373-73-7910,Alex,Yangon,Member,Female,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37:00 AM,Ewallet,604.17,4.761905,30.2085,5.3
2,699-14-3026,Giza,Naypyitaw,Member,Female,Electronic accessories,85.39,7,29.8865,627.6165,3/25/2019,6:30:00 PM,Ewallet,597.73,4.761905,29.8865,4.1
3,315-22-5665,Giza,Naypyitaw,Member,Female,Home and lifestyle,73.56,10,36.7800,772.3800,2/24/2019,11:38:00 AM,Ewallet,735.60,4.761905,36.7800,8.0
4,829-34-3910,Alex,Yangon,Member,Female,Health and beauty,71.38,10,35.6900,749.4900,3/29/2019,7:21:00 PM,Cash,713.80,4.761905,35.6900,5.7

In [28]:
query = """
SELECT City,
SUM(Sales) AS Total_Sales
FROM sales
GROUP BY City;
"""

city_sales = pd.read_sql(query, conn)

print(city_sales)

        City  Total_Sales
0   Mandalay  106197.6720
1  Naypyitaw  110568.7065
2     Yangon  106200.3705

In [29]:
city_sales.to_csv("../data/processed/city_sales.csv", index=False)

print("CSV Saved Successfully!")

CSV Saved Successfully!

In [30]:
conn.close()

print("Database Closed Successfully!")

Database Closed Successfully!